[[language]]
name = "rust"
auto-format = true
indent = { tab-width = 4, unit = "    " }
formatter = { command = "rustfmt" }
language-servers = ["rust-analyzer"]

[[language]]
name = "python"
auto-format = true
indent = { tab-width = 4, unit = "    " }
formatter = { command = "black", args = ["-"] }
language-servers = ["pylsp"]

[[language]]
name = "toml"
auto-format = true
indent = { tab-width = 2, unit = "  " }
formatter = { command = "taplo", args = ["format", "-"] }

[[langauge]]
name = "yaml"
auto-format = true
indent = { tab-width = 2, unit = "  " }
formatter = { command = "prettier", args = ["--parser", "yaml"] }

[[language]]
name = "json"
auto-format = true
indent = { tab-width = 4, unit = "    " }
formatter = { command = "prettier", args = ["--parser", "json"] }
